name: allycat-rag-graphrag

services:
  - name: web
    github:
      repo: niloydebbarma-code/allycat-rag-graphrag
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile
    
    http_port: 8081
    
    health_check:
      http_path: /
      port: 8081
      initial_delay_seconds: 240
      period_seconds: 60
      timeout_seconds: 30
      success_threshold: 3
      failure_threshold: 1
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    envs:
      - key: AUTO_RUN_PIPELINE
        value: "true"
      - key: LLM_PROVIDER
        value: "cerebras"
      - key: CEREBRAS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: VECTOR_DB_TYPE
        value: "zilliz"
      - key: ZILLIZ_URI
        scope: RUN_TIME
        type: SECRET
      - key: ZILLIZ_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: NEO4J_URI
        scope: RUN_TIME
        type: SECRET
      - key: NEO4J_USERNAME
        scope: RUN_TIME
        type: SECRET
      - key: NEO4J_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: WEBSITE_URL
        value: "https://docs.ray.io/en/latest/"
